apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q3yomlmbb-go 
  janus-idp.io/tekton: q3yomlmbb-go
  backstage.io/kubernetes-id: q3yomlmbb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q3yomlmbb-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml